### ISSUE TITLE
Erroring out during the execution  

### ISSUE THREAD

**Issue by SriMun16** [JimLiu96/MITGNN#1]
Hi Zhiwei,
My python environment consists of the following packages(posting only relevant ones):
`python==3.6.10  tensorboard==1.15.0
tensorflow==1.15.0
tensorflow-estimator==1.15.1 pandas==1.1.5 numpy==1.19.2 sklearn==0.24.2`
on a mac OS 11.3 Big Sur

I tried executing your code as per your suggestion
`python MITGNN.py --dataset inscart_3 --regs [1e-3] --alg_type intent_conv --embed_size 64 --layer_size [64,64,64] --lr 0.0001 --save_flag 1 --pretrain 0 --batch_size 20 --num_intent 5 --epoch 1000`

I see the following error. (i see the same error for different batch sizes)
```

tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 2 of dimension 0 out of bounds.
	 [[{{node strided_slice_21}}]]
```
I have attached the full error file. Please let me know if you have any inputs. Thank you!
[error1.txt](https://github.com/JimLiu96/MITGNN/files/6870734/error1.txt)

**Comment by JimLiu96** [comment]
Hi Srimun,

The error is due to the "--mess_dropout" argument is not given. I have already updated the given script in this repo. You can try this new one.

**Comment by SriMun16** [comment]
resolved. thank you so much!!
